name: QUEEN ELISA-MD BOT

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Install System Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg imagemagick chromium-browser

    - name: Install Bot Dependencies
      run: npm install

    - name: Create Auth Session Directory
      run: mkdir -p auth_info_baileys

    - name: Decode and Inject WhatsApp Session
      run: |
        RAW_SESSION="P5xkUZYL#kmvWI2vvod2HmcT_qDBzNHq2GD44jeHfakgGubLJPwU"
        echo "$RAW_SESSION" > auth_info_baileys/creds.json
      continue-on-error: true

    - name: Start QUEEN ELISA-MD Engine
      run: node index.js
